package com.server.ordering.domain;

public enum FoodCategory {
    NONE, KOREAN_FOOD, BUNSIK, CAFE_DESSERT, PORK_CUTLET_ROW_FISH_SUSHI, CHICKEN, PIZZA,
    ASIAN_FOOD_WESTERN_FOOD, CHINESE_FOOD, JOKBAL_BOSSAM, JJIM_TANG, FAST_FOOD
}
